[package]
name = "log4rs-rolling-file"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]

[dependencies]
antidote = "0.1"
log = "0.3"
log4rs = "0.4"
serde = "0.7"
serde-value = "0.2"
